In [1]:
import numpy as np

In [2]:
x = np.array([[[[1, 2],[3, 4]],[[5, 6],[7, 8]]],
              [[[8, 7],[6, 5]],[[4, 3],[2, 1]]]])

In [3]:
y = x.reshape((8,2))

In [4]:
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [8, 7],
       [6, 5],
       [4, 3],
       [2, 1]])

In [8]:
q,r = np.linalg.qr(y,mode='complete')

In [9]:
q

array([[-0.070014  , -0.362266  , -0.38175059, -0.51787412, -0.50305241,
        -0.36692887, -0.23080533, -0.0946818 ],
       [-0.21004201, -0.37619931, -0.34654925, -0.33979524,  0.39045035,
         0.38369633,  0.37694232,  0.37018831],
       [-0.35007002, -0.39013261,  0.81857755, -0.21899045, -0.06276951,
        -0.02520152,  0.01236648,  0.04993447],
       [-0.49009803, -0.40406592, -0.22441375,  0.71934576, -0.14114947,
        -0.08490897, -0.02866848,  0.02757202],
       [-0.56011203,  0.29956611, -0.09802095, -0.1818242 ,  0.55329981,
        -0.36289694, -0.27909369, -0.19529044],
       [-0.42008403,  0.31349942, -0.05502966, -0.12016041, -0.36832024,
         0.69681051, -0.23805873, -0.17292798],
       [-0.28005602,  0.32743273, -0.01203836, -0.05849662, -0.28994028,
        -0.24348203,  0.80297622, -0.15056552],
       [-0.14002801,  0.34136604,  0.03095293,  0.00316718, -0.21156033,
        -0.18377457, -0.15598882,  0.87179693]])

In [10]:
r

array([[-14.28285686, -14.00280084],
       [  0.        ,  -2.81452814],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ]])

In [2]:
test = np.ones((2,2),dtype=complex)

In [3]:
test

array([[1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j]])