In [104]:
import numpy as np
from itertools import product

In [105]:
x = np.array([[[[1, 2],[3, 4]],[[5, 6],[7, 8]]],
              [[[8, 7],[6, 5]],[[4, 3],[2, 1]]]])

In [106]:
# convert x to 4x4 matrix
y = x.reshape((4,4))

In [107]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [108]:
# perform svd for y
uy,sy,vy = np.linalg.svd(y, full_matrices=True)

In [109]:
# keep the largest 2 sv's only

In [110]:
sy = sy[0:2]
diag_sy = np.diag(sy)
sy1 = np.sqrt(diag_sy)
sy2 = np.sqrt(diag_sy)

In [111]:
diag_sy

array([[19.6977156 ,  0.        ],
       [ 0.        ,  4.47213595]])

In [112]:
sy1

array([[4.43821086, 0.        ],
       [0.        , 2.11474253]])

In [113]:
uy = uy[:,0:2]
uy

array([[-0.25383654, -0.5       ],
       [-0.65997501, -0.5       ],
       [-0.65997501,  0.5       ],
       [-0.25383654,  0.5       ]])

In [114]:
vy = vy[0:2,:]
vy

array([[-0.5       , -0.5       , -0.5       , -0.5       ],
       [ 0.67082039,  0.2236068 , -0.2236068 , -0.67082039]])

In [115]:
mat1 = np.matmul(uy,sy1)
mat2 = np.matmul(sy2,vy)

In [116]:
mat1

array([[-1.12658009, -1.05737126],
       [-2.92910824, -1.05737126],
       [-2.92910824,  1.05737126],
       [-1.12658009,  1.05737126]])

In [117]:
mat2

array([[-2.21910543, -2.21910543, -2.21910543, -2.21910543],
       [ 1.41861241,  0.4728708 , -0.4728708 , -1.41861241]])

In [118]:
# verify svd result
np.matmul(mat1,mat2)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [8., 7., 6., 5.],
       [4., 3., 2., 1.]])

In [119]:
tensor1 = mat1.reshape((2,2,2))
tensor2 = mat2.reshape((2,2,2))

In [120]:
tensor2[0,1]

array([-2.21910543, -2.21910543])

In [121]:
result = np.einsum('lin,njk->lijk',tensor1,tensor2)

In [122]:
result

array([[[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]],


       [[[8., 7.],
         [6., 5.]],

        [[4., 3.],
         [2., 1.]]]])

In [123]:
x = np.array([[[[1, 2],[3, 4]],[[5, 6],[7, 8]]],
              [[[8, 7],[6, 5]],[[4, 3],[2, 1]]]])

In [124]:
# convert x to 4x4 matrix
y = (np.einsum('lijk->ijkl',x)).reshape((4,4))

In [125]:
y

array([[1, 8, 2, 7],
       [3, 6, 4, 5],
       [5, 4, 6, 3],
       [7, 2, 8, 1]])

In [126]:
# perform svd for y
uy,sy,vy = np.linalg.svd(y, full_matrices=True)

In [127]:
# keep the largest 2 sv's only

In [128]:
sy = sy[0:2]
diag_sy = np.diag(sy)
sy1 = np.sqrt(diag_sy)
sy2 = np.sqrt(diag_sy)

In [129]:
diag_sy

array([[18.11077028,  0.        ],
       [ 0.        ,  8.94427191]])

In [130]:
sy1

array([[4.25567507, 0.        ],
       [0.        , 2.99069756]])

In [131]:
uy = uy[:,0:2]
uy

array([[-0.5       , -0.67082039],
       [-0.5       , -0.2236068 ],
       [-0.5       ,  0.2236068 ],
       [-0.5       ,  0.67082039]])

In [132]:
vy = vy[0:2,:]
vy

array([[-0.4417261 , -0.55215763, -0.55215763, -0.4417261 ],
       [ 0.5       , -0.5       ,  0.5       , -0.5       ]])

In [133]:
mat1 = np.matmul(uy,sy1)
mat2 = np.matmul(sy2,vy)

In [134]:
mat1

array([[-2.12783753, -2.00622091],
       [-2.12783753, -0.6687403 ],
       [-2.12783753,  0.6687403 ],
       [-2.12783753,  2.00622091]])

In [135]:
mat2

array([[-1.87984277, -2.34980346, -2.34980346, -1.87984277],
       [ 1.49534878, -1.49534878,  1.49534878, -1.49534878]])

In [136]:
# verify svd result
np.matmul(mat1,mat2)

array([[1., 8., 2., 7.],
       [3., 6., 4., 5.],
       [5., 4., 6., 3.],
       [7., 2., 8., 1.]])

In [137]:
tensor1 = mat1.reshape((2,2,2))
tensor2 = mat2.reshape((2,2,2))

In [138]:
tensor2[0,1]

array([-2.34980346, -1.87984277])

In [139]:
result = np.einsum('ijn,nkl->lijk',tensor1,tensor2)

In [140]:
result

array([[[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]],


       [[[8., 7.],
         [6., 5.]],

        [[4., 3.],
         [2., 1.]]]])